//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebApi_12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int pur_id { get; set; }
        public string pur_no { get; set; }
        public System.DateTime date { get; set; }
        public double total_amount { get; set; }
    }
}
